### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-1-Azza** [UMSF-K13-1-Azza/Azza#1]
[K13-1-Azza.docx](https://github.com/UMSF-K13-1-Azza/Azza/files/290767/K13-1-Azza.docx)

**Comment by Smoktii** [comment]
Ок

**Comment by UMSF-K13-1-Azza** [comment]
примите еще раз пжл заявку,я случайно удалил вас,я добавлю Вас в Assignees
